### ISSUE TITLE
pandownload仍然无法使用，请问大佬如何解决？

### ISSUE THREAD

**Issue by whrwhr258** [zgcwkj/PanDownloadOpen#3]
谢谢!!!
![QQ截图20200418204614](https://user-images.githubusercontent.com/63903634/79638936-f6a30380-81ba-11ea-8584-4bff615d1a7b.jpg)

**Comment by zgcwkj** [comment]
你的版本问题吧，我这个是基于 2.2.2 写的。
你可以下载个新的试试。

**Comment by zgcwkj** [comment]
下载这个试试：[https://github.com/zgcwkj/PanDownloadOpen/releases/download/1.0.0/PanDownload.zip](https://github.com/zgcwkj/PanDownloadOpen/releases/download/1.0.0/PanDownload.zip)
蓝奏云下载：[https://www.lanzous.com/iblbc2h](https://www.lanzous.com/iblbc2h)

**Comment by whrwhr258** [comment]
谢谢

**Comment by zgcwkj** [comment]
> 谢谢

不用，应该的~~~🤞
